extend type Batch {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Batch", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Batch`.`shelter`. It must match the value of `Shelter`.`id`. See `@ref` for how to customize it.
  """
  shelterId: UUID! @fdc_generated(from: "Batch.shelter", purpose: IMPLICIT_REF_FIELD)
}
extend type Donation {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Donation", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Donation`.`donor`. It must match the value of `Donor`.`id`. See `@ref` for how to customize it.
  """
  donorId: UUID! @fdc_generated(from: "Donation.donor", purpose: IMPLICIT_REF_FIELD)
}
extend type Donor {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Donor", purpose: IMPLICIT_KEY_FIELD)
}
extend type Product {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Product", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`batch`. It must match the value of `Batch`.`id`. See `@ref` for how to customize it.
  """
  batchId: UUID @fdc_generated(from: "Product.batch", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`donation`. It must match the value of `Donation`.`id`. See `@ref` for how to customize it.
  """
  donationId: UUID! @fdc_generated(from: "Product.donation", purpose: IMPLICIT_REF_FIELD)
}
extend type Shelter {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Shelter", purpose: IMPLICIT_KEY_FIELD)
}
