extend type Query {
  """
  ✨ Look up a single `Batch` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  batch(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Batch_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Batch_FirstRow
  ): Batch @fdc_generated(from: "Batch", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Donation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  donation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Donation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Donation_FirstRow
  ): Donation @fdc_generated(from: "Donation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Donor` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  donor(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Donor_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Donor_FirstRow
  ): Donor @fdc_generated(from: "Donor", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Product` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  product(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product @fdc_generated(from: "Product", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProductCatalog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  productCatalog(
    """
    The key used to identify the object.
    """
    key: ProductCatalog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductCatalog_FirstRow
  ): ProductCatalog @fdc_generated(from: "ProductCatalog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Shelter` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  shelter(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Shelter_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Shelter_FirstRow
  ): Shelter @fdc_generated(from: "Shelter", purpose: QUERY_SINGLE)
  """
  ✨ List `Batch` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  batches(
    """
    Filter condition to narrow down the query results.
    """
    where: Batch_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Batch_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Batch_Having
  ): [Batch!]! @fdc_generated(from: "Batch", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Donation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  donations(
    """
    Filter condition to narrow down the query results.
    """
    where: Donation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Donation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Donation_Having
  ): [Donation!]! @fdc_generated(from: "Donation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Donor` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  donors(
    """
    Filter condition to narrow down the query results.
    """
    where: Donor_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Donor_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Donor_Having
  ): [Donor!]! @fdc_generated(from: "Donor", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Product` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  products(
    """
    Filter condition to narrow down the query results.
    """
    where: Product_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Product_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Product_Having
  ): [Product!]! @fdc_generated(from: "Product", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProductCatalog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  productCatalogs(
    """
    Filter condition to narrow down the query results.
    """
    where: ProductCatalog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProductCatalog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProductCatalog_Having
  ): [ProductCatalog!]! @fdc_generated(from: "ProductCatalog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Shelter` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  shelters(
    """
    Filter condition to narrow down the query results.
    """
    where: Shelter_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Shelter_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Shelter_Having
  ): [Shelter!]! @fdc_generated(from: "Shelter", purpose: QUERY_MULTIPLE)
}
