extend type Batch {
  """
  ✨ List `Product` objects in a one-to-many relationship (where `Product`.`batch` is this object).
  """
  products_on_batch(
    """
    Filter condition to narrow down the query results.
    """
    where: Product_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Product_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Product_Having
  ): [Product!]! @fdc_generated(from: "Product.batch", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Batch", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Batch` table.
  """
  _count: Int! @fdc_generated(from: "Batch.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `deliveredAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  deliveredAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.deliveredAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `finalizedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  finalizedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.finalizedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `shelterId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  shelterId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.shelterId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `shippedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  shippedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.shippedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Batch` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Batch.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Batch` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Batch.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `deliveredAt` field in the `Batch` table.
  """
  deliveredAt_min: Timestamp @fdc_generated(from: "Batch.deliveredAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `finalizedAt` field in the `Batch` table.
  """
  finalizedAt_min: Timestamp @fdc_generated(from: "Batch.finalizedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `shippedAt` field in the `Batch` table.
  """
  shippedAt_min: Timestamp @fdc_generated(from: "Batch.shippedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Batch` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Batch.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Batch` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Batch.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `deliveredAt` field in the `Batch` table.
  """
  deliveredAt_max: Timestamp @fdc_generated(from: "Batch.deliveredAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `finalizedAt` field in the `Batch` table.
  """
  finalizedAt_max: Timestamp @fdc_generated(from: "Batch.finalizedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `shippedAt` field in the `Batch` table.
  """
  shippedAt_max: Timestamp @fdc_generated(from: "Batch.shippedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Batch` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Batch.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Batch.id", purpose: ENTITY_ID)
}
extend type Donation {
  """
  ✨ List `Product` objects in a one-to-many relationship (where `Product`.`donation` is this object).
  """
  products_on_donation(
    """
    Filter condition to narrow down the query results.
    """
    where: Product_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Product_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Product_Having
  ): [Product!]! @fdc_generated(from: "Product.donation", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Donation", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Donation` table.
  """
  _count: Int! @fdc_generated(from: "Donation.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `date` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  date_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.date", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `donationRequestId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  donationRequestId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.donationRequestId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `donorId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  donorId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.donorId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `method` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  method_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.method", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `processedBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  processedBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.processedBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donation` table where the `warehouseReference` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  warehouseReference_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donation.warehouseReference", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Donation` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Donation.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `date` field in the `Donation` table.
  """
  date_min: Date @fdc_generated(from: "Donation.date", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Donation` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Donation.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Donation` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Donation.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `date` field in the `Donation` table.
  """
  date_max: Date @fdc_generated(from: "Donation.date", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Donation` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Donation.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Donation.id", purpose: ENTITY_ID)
}
extend type Donor {
  """
  ✨ List `Donation` objects in a one-to-many relationship (where `Donation`.`donor` is this object).
  """
  donations_on_donor(
    """
    Filter condition to narrow down the query results.
    """
    where: Donation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Donation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Donation_Having
  ): [Donation!]! @fdc_generated(from: "Donation.donor", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Donor", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Donor` table.
  """
  _count: Int! @fdc_generated(from: "Donor.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `city` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  city_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.city", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `donationCount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  donationCount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.donationCount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `fullName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fullName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.fullName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `instagramHandle` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  instagramHandle_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.instagramHandle", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `linkedRequestId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  linkedRequestId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.linkedRequestId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `phone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.phone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `smsOptIn` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  smsOptIn_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.smsOptIn", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `state` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  state_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.state", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Donor` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Donor.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Sum the `donationCount` field in the `Donor` table.
  """
  donationCount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Donor.donationCount", purpose: QUERY_SUM)
  """
  ✨ Average the `donationCount` field in the `Donor` table.
  """
  donationCount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Donor.donationCount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Donor` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Donor.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `donationCount` field in the `Donor` table.
  """
  donationCount_min: Int @fdc_generated(from: "Donor.donationCount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Donor` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Donor.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Donor` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Donor.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `donationCount` field in the `Donor` table.
  """
  donationCount_max: Int @fdc_generated(from: "Donor.donationCount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Donor` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Donor.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Donor.id", purpose: ENTITY_ID)
}
extend type Product {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Product", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Product` table.
  """
  _count: Int! @fdc_generated(from: "Product.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `barcode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  barcode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.barcode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `batchId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  batchId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.batchId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `brand` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  brand_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.brand", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `colorCategory` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  colorCategory_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.colorCategory", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `color` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  color_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.color", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `details` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  details_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.details", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `donationId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  donationId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.donationId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `expirationDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  expirationDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.expirationDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `keyIngredients` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  keyIngredients_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.keyIngredients", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `price` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  price_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.price", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `quantity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  quantity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.quantity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.type", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Sum the `quantity` field in the `Product` table.
  """
  quantity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Product.quantity", purpose: QUERY_SUM)
  """
  ✨ Average the `quantity` field in the `Product` table.
  """
  quantity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.quantity", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Product` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Product.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `details` field in the `Product` table.
  """
  details_min: Any @fdc_generated(from: "Product.details", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `expirationDate` field in the `Product` table.
  """
  expirationDate_min: Date @fdc_generated(from: "Product.expirationDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `quantity` field in the `Product` table.
  """
  quantity_min: Int @fdc_generated(from: "Product.quantity", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Product` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Product.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Product` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Product.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `details` field in the `Product` table.
  """
  details_max: Any @fdc_generated(from: "Product.details", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `expirationDate` field in the `Product` table.
  """
  expirationDate_max: Date @fdc_generated(from: "Product.expirationDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `quantity` field in the `Product` table.
  """
  quantity_max: Int @fdc_generated(from: "Product.quantity", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Product` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Product.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Product.id", purpose: ENTITY_ID)
}
extend type ProductCatalog {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ProductCatalog", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ProductCatalog` table.
  """
  _count: Int! @fdc_generated(from: "ProductCatalog.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `barcode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  barcode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.barcode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `brand` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  brand_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.brand", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `color` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  color_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.color", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `keyIngredients` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  keyIngredients_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.keyIngredients", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `lastUsedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastUsedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.lastUsedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `price` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  price_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.price", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `source` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  source_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.source", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `timesUsed` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timesUsed_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.timesUsed", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ProductCatalog` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ProductCatalog.type", purpose: QUERY_COUNT)
  """
  ✨ Sum the `timesUsed` field in the `ProductCatalog` table.
  """
  timesUsed_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "ProductCatalog.timesUsed", purpose: QUERY_SUM)
  """
  ✨ Average the `timesUsed` field in the `ProductCatalog` table.
  """
  timesUsed_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "ProductCatalog.timesUsed", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `ProductCatalog` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "ProductCatalog.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lastUsedAt` field in the `ProductCatalog` table.
  """
  lastUsedAt_min: Timestamp @fdc_generated(from: "ProductCatalog.lastUsedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `timesUsed` field in the `ProductCatalog` table.
  """
  timesUsed_min: Int @fdc_generated(from: "ProductCatalog.timesUsed", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `ProductCatalog` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "ProductCatalog.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lastUsedAt` field in the `ProductCatalog` table.
  """
  lastUsedAt_max: Timestamp @fdc_generated(from: "ProductCatalog.lastUsedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `timesUsed` field in the `ProductCatalog` table.
  """
  timesUsed_max: Int @fdc_generated(from: "ProductCatalog.timesUsed", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ProductCatalog.barcode", purpose: ENTITY_ID)
}
extend type Shelter {
  """
  ✨ List `Batch` objects in a one-to-many relationship (where `Batch`.`shelter` is this object).
  """
  batches_on_shelter(
    """
    Filter condition to narrow down the query results.
    """
    where: Batch_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Batch_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Batch_Having
  ): [Batch!]! @fdc_generated(from: "Batch.shelter", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Shelter", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Shelter` table.
  """
  _count: Int! @fdc_generated(from: "Shelter.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `addressLine1` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  addressLine1_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.addressLine1", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `addressLine2` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  addressLine2_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.addressLine2", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `capacityPerBatch` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  capacityPerBatch_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.capacityPerBatch", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `city` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  city_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.city", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `contactEmail` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  contactEmail_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.contactEmail", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `contactName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  contactName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.contactName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `contactPhone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  contactPhone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.contactPhone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `isActive` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isActive_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.isActive", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `postalCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  postalCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.postalCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `state` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  state_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.state", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shelter` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shelter.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Sum the `capacityPerBatch` field in the `Shelter` table.
  """
  capacityPerBatch_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Shelter.capacityPerBatch", purpose: QUERY_SUM)
  """
  ✨ Average the `capacityPerBatch` field in the `Shelter` table.
  """
  capacityPerBatch_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Shelter.capacityPerBatch", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `capacityPerBatch` field in the `Shelter` table.
  """
  capacityPerBatch_min: Int @fdc_generated(from: "Shelter.capacityPerBatch", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Shelter` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Shelter.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Shelter` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Shelter.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `capacityPerBatch` field in the `Shelter` table.
  """
  capacityPerBatch_max: Int @fdc_generated(from: "Shelter.capacityPerBatch", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Shelter` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Shelter.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Shelter` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Shelter.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Shelter.id", purpose: ENTITY_ID)
}
